// Generated by scripts/import-portraits.mjs: the advisors who have a portrait
// in public/advisors/. Don't edit by hand; re-run the script instead.
export const PORTRAIT_SLUGS = [
  "amara-vance",
  "aris-chen",
  "arthur-penrose",
  "daniel-okoye",
  "eleanor-whitfield",
  "felix-hart",
  "grace-bennett",
  "helena-vogt",
  "julian-rhodes",
  "kai-nakamura",
  "lena-fisher",
  "marcus-delgado",
  "margaret-ashworth",
  "naomi-clarke",
  "nathan-cole",
  "priya-nair",
  "rafael-duarte",
  "sofia-marchetti",
  "theo-lindqvist",
  "tomas-berg",
  "victor-hale",
  "warren-bishop"
];
