import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { CheckSquare, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import PageHeader from "@/components/PageHeader";
import EmptyState from "@/components/EmptyState";
import AdvisorAvatar from "@/components/AdvisorAvatar";

const COLUMNS = [
  { key: "todo", label: "To Do" },
  { key: "in_progress", label: "In Progress" },
  { key: "review", label: "Review" },
  { key: "done", label: "Done" },
];

export default function Tasks() {
  const { companyId } = useParams();
  const [items, setItems] = useState(null);
  const [advisors, setAdvisors] = useState([]);
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ title: "", assigned_to: "" });

  const load = () => base44.entities.Task.filter({ company_id: companyId }, "-created_date", 200).then(setItems);
  useEffect(() => { load(); base44.entities.Advisor.filter({ company_id: companyId }, "-created_date", 100).then(setAdvisors); }, [companyId]);

  const create = async () => {
    if (!form.title.trim()) return;
    await base44.entities.Task.create({ company_id: companyId, title: form.title, assigned_to: form.assigned_to, created_by: "Founder", status: "todo" });
    setForm({ title: "", assigned_to: "" }); setOpen(false); load();
  };

  const move = async (task, status) => { await base44.entities.Task.update(task.id, { status }); load(); };
  const accentOf = (name) => advisors.find((a) => a.name === name)?.accent || "#7a5c3e";

  return (
    <div>
      <PageHeader eyebrow="Owned work" title="Tasks" description="Assigned by you or generated by your advisors from the boardroom.">
        <Button onClick={() => setOpen(true)} className="rounded-full px-5"><Plus className="w-4 h-4 mr-1.5" /> New task</Button>
      </PageHeader>
      {items === null ? <div className="h-40 rounded-2xl bg-secondary/60 animate-pulse" />
        : items.length === 0 ? <EmptyState icon={CheckSquare} title="No tasks yet" description="Create a task, or let your board assign work during a meeting." action={<Button onClick={() => setOpen(true)} className="rounded-full px-6"><Plus className="w-4 h-4 mr-1.5" /> New task</Button>} />
        : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {COLUMNS.map((col) => {
            const colItems = items.filter((t) => t.status === col.key);
            return (
              <div key={col.key} className="bg-secondary/40 rounded-2xl p-3">
                <div className="flex items-center justify-between px-2 mb-3">
                  <span className="text-sm font-medium">{col.label}</span>
                  <span className="text-xs text-muted-foreground">{colItems.length}</span>
                </div>
                <div className="space-y-2 min-h-[40px]">
                  {colItems.map((t) => {
                    const idx = COLUMNS.findIndex((c) => c.key === col.key);
                    return (
                      <div key={t.id} className="bg-card border border-border/70 rounded-xl p-3 rise-in">
                        <p className="text-sm leading-snug mb-2">{t.title}</p>
                        <div className="flex items-center justify-between">
                          {t.assigned_to ? <div className="flex items-center gap-1.5"><AdvisorAvatar name={t.assigned_to} accent={accentOf(t.assigned_to)} size="sm" /><span className="text-[11px] text-muted-foreground truncate max-w-[70px]">{t.assigned_to.split(" ")[0]}</span></div> : <span className="text-[11px] text-muted-foreground">Unassigned</span>}
                          <div className="flex gap-1">
                            {idx > 0 && <button onClick={() => move(t, COLUMNS[idx-1].key)} className="text-xs text-muted-foreground hover:text-foreground px-1">‹</button>}
                            {idx < COLUMNS.length-1 && <button onClick={() => move(t, COLUMNS[idx+1].key)} className="text-xs text-muted-foreground hover:text-foreground px-1">›</button>}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      )}

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader><DialogTitle className="font-display text-2xl font-light">New task</DialogTitle></DialogHeader>
          <div className="space-y-4 pt-2">
            <div><Label className="mb-1.5 block">Task</Label><Input value={form.title} onChange={(e)=>setForm(f=>({...f,title:e.target.value}))} autoFocus /></div>
            <div><Label className="mb-1.5 block">Assign to</Label>
              <select value={form.assigned_to} onChange={(e)=>setForm(f=>({...f,assigned_to:e.target.value}))} className="w-full h-10 rounded-md border border-input bg-background px-3 text-sm">
                <option value="">Unassigned</option>{advisors.map(a=><option key={a.id}>{a.name}</option>)}
              </select>
            </div>
            <div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={create} disabled={!form.title.trim()}>Create</Button></div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}