import React, { useEffect, useState } from "react";
import { useParams, useOutletContext } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { CheckSquare, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import PageHeader from "@/components/PageHeader";
import EmptyState from "@/components/EmptyState";
import TaskCard from "@/components/tasks/TaskCard";
import DocumentDetailDialog from "@/components/documents/DocumentDetailDialog";
import { generateDeliverable } from "@/lib/deliverables";
import { DOCUMENT_TYPES } from "@/lib/documents";

const COLUMNS = [
  { key: "todo", label: "To Do" },
  { key: "in_progress", label: "In Progress" },
  { key: "review", label: "Review" },
  { key: "done", label: "Done" },
];

export default function Tasks() {
  const { companyId } = useParams();
  const { company } = useOutletContext();
  const [items, setItems] = useState(null);
  const [advisors, setAdvisors] = useState([]);
  const [projects, setProjects] = useState([]);
  const [open, setOpen] = useState(false);
  const [executingId, setExecutingId] = useState(null);
  const [viewDoc, setViewDoc] = useState(null);
  const [form, setForm] = useState({ title: "", assigned_to: "", project_id: "" });

  const load = () => base44.entities.Task.filter({ company_id: companyId }, "-created_date", 200).then(setItems);
  useEffect(() => { load(); base44.entities.Advisor.filter({ company_id: companyId }, "-created_date", 100).then(setAdvisors); base44.entities.Project.filter({ company_id: companyId }, "-created_date", 100).then(setProjects); }, [companyId]);

  const create = async () => {
    if (!form.title.trim()) return;
    await base44.entities.Task.create({ company_id: companyId, title: form.title, assigned_to: form.assigned_to, project_id: form.project_id || undefined, created_by: "Founder", status: "todo" });
    setForm({ title: "", assigned_to: "", project_id: "" }); setOpen(false); load();
  };

  const move = async (task, dir) => {
    const idx = COLUMNS.findIndex((c) => c.key === task.status);
    const next = dir === "forward" ? COLUMNS[idx + 1]?.key : COLUMNS[idx - 1]?.key;
    if (!next) return;
    await base44.entities.Task.update(task.id, { status: next }); load();
  };

  const detectDocType = (task) => {
    const text = `${task.title} ${task.description || ""}`.toLowerCase();
    const financeTerms = ["financial model", "unit economics", "cash flow", "p&l", "profit and loss", "budget", "forecast", "margin", "breakeven", "break-even", "revenue model"];
    if (financeTerms.some((t) => text.includes(t))) return "Financial Model";
    return "Report";
  };

  const execute = async (task) => {
    const advisor = advisors.find((a) => a.name === task.assigned_to);
    if (!advisor) return;
    setExecutingId(task.id);
    await base44.entities.Task.update(task.id, { status: "in_progress", delegated_back: false });
    load();
    try {
      const result = await generateDeliverable({
        companyId,
        taskId: task.id,
        advisorId: advisor.id,
        documentType: detectDocType(task),
        topic: task.title,
      });
      load();
    } catch (e) {
      await base44.entities.Task.update(task.id, { status: "todo", delegated_back: true, blocker: e.message || "Generation failed" });
      load();
    } finally {
      setExecutingId(null);
    }
  };

  const completeForFounder = async (task) => {
    await base44.entities.Task.update(task.id, { status: "done" }); load();
  };

  return (
    <div>
      <PageHeader eyebrow="Owned work" title="Tasks" description="Assigned by you or generated by your advisors from the boardroom.">
        <Button onClick={() => setOpen(true)} className="rounded-full px-5"><Plus className="w-4 h-4 mr-1.5" /> New task</Button>
      </PageHeader>
      {items === null ? <div className="h-40 rounded-2xl bg-secondary/60 animate-pulse" />
        : items.length === 0 ? <EmptyState icon={CheckSquare} title="No tasks yet" description="Create a task, or let your board assign work during a meeting." action={<Button onClick={() => setOpen(true)} className="rounded-full px-6"><Plus className="w-4 h-4 mr-1.5" /> New task</Button>} />
        : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {COLUMNS.map((col) => {
            const colItems = items.filter((t) => t.status === col.key);
            return (
              <div key={col.key} className="bg-secondary/40 rounded-2xl p-3">
                <div className="flex items-center justify-between px-2 mb-3">
                  <span className="text-sm font-medium">{col.label}</span>
                  <span className="text-xs text-muted-foreground">{colItems.length}</span>
                </div>
                <div className="space-y-2 min-h-[40px]">
                  {colItems.map((t) => (
                    <TaskCard
                      key={t.id}
                      task={t}
                      advisors={advisors}
                      executing={executingId === t.id}
                      onExecute={execute}
                      onCompleteFounder={completeForFounder}
                      onMove={move}
                      onOpenDocument={async (docId) => {
                        const d = await base44.entities.Document.get(docId);
                        setViewDoc(d);
                      }}
                      canBack={COLUMNS.findIndex((c) => c.key === col.key) > 0}
                      canForward={COLUMNS.findIndex((c) => c.key === col.key) < COLUMNS.length - 1}
                    />
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      )}

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader><DialogTitle className="font-display text-2xl font-light">New task</DialogTitle></DialogHeader>
          <div className="space-y-4 pt-2">
            <div><Label className="mb-1.5 block">Task</Label><Input value={form.title} onChange={(e)=>setForm(f=>({...f,title:e.target.value}))} autoFocus /></div>
            <div><Label className="mb-1.5 block">Assign to</Label>
              <select value={form.assigned_to} onChange={(e)=>setForm(f=>({...f,assigned_to:e.target.value}))} className="w-full h-10 rounded-md border border-input bg-background px-3 text-sm">
                <option value="">Unassigned</option>{advisors.map(a=><option key={a.id}>{a.name}</option>)}
              </select>
            </div>
            <div><Label className="mb-1.5 block">Project</Label>
              <select value={form.project_id} onChange={(e)=>setForm(f=>({...f,project_id:e.target.value}))} className="w-full h-10 rounded-md border border-input bg-background px-3 text-sm">
                <option value="">None</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}
              </select>
            </div>
            <div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={create} disabled={!form.title.trim()}>Create</Button></div>
          </div>
        </DialogContent>
      </Dialog>

      {viewDoc && (
        <DocumentDetailDialog
          doc={viewDoc}
          advisors={advisors}
          company={company}
          onClose={() => setViewDoc(null)}
          onRefresh={async () => {
            const d = await base44.entities.Document.get(viewDoc.id);
            setViewDoc(d);
            load();
          }}
        />
      )}
    </div>
  );
}